[project]
name = "project_backend"
version = "0.1.0"
requires-python = ">=3.10,<3.13"
dependencies = [
	"fastapi==0.128.0",
	"uvicorn==0.22.0",
	"supabase==2.27.2",
	"pydantic-settings==2.12.0"
]

[tool.vercel.scripts]